---
- name: Configure the vms
  hosts: all
  roles:
    - configuration

- name: Install Docker
  hosts: all
  roles:
    - installDocker
  become_user: docker
  become: yes

- name: Setup secured API connection
  hosts: all
  roles:
    - setupSecureConnection
  become_user: docker
  become: yes

- name: initialize Docker Swarm
  hosts: swarm-manager
  roles:
    - swarmInit
  become_user: docker
  become: yes

- name: add workers to the swarm
  hosts: swarm-workers
  roles:
    - swarmJoin
  become_user: docker
  become: yes


