---
- name: Configure the vms
  hosts: all
  roles:
    - configuration

- name: Install Docker
  hosts: all
  roles:
    - install_docker

- name: Setup secured API connection
  hosts: all
  roles:
    - setup_secure_connection

- name: initialize Docker Swarm
  hosts: swarm-manager
  roles:
    - swarm_init

- name: add workers to the swarm
  hosts: swarm-workers
  roles:
    - swarm_join


