---
- name: Configure the vms
  hosts: all
  roles:
    - configuration
  
- name: Install Docker
  hosts: all
  roles: 
    - install-docker
  become_user: docker

- name: Setup secured API connection
  hosts: swarm-manager
  roles:
    - setup_secure_connection
  become_user: docker

- name: initialize Docker Swarm
  hosts: swarm-manager
  roles:
    - swarm-init
  become_user: docker

- name: add workers to the swarm-init
  hosts: swarm-workers
  roles:
    - swarm-join
  become_user: docker


