---
- name: ensure github.com is a known host
  become: yes
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: ""
    regexp: "^github\\.com"
    mode: 0600


- name: Install Packages
  yum:
    name:
      - 'openssl'
      - epel-release
      - python3
    state: present
    update_cache: yes


