---
#docker package
docker_edition: ce
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

#docker repo
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg
docker_yum_repo_url: ttps://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo

#edge-test
docker_yum_repo_enable_edge: '0'
docker_yum_repo_enable_test: '0'



#docker compose
docker_compose_path: /usr/local/bin/docker-compose
docker_compose_version: "1.26.0"